# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('base_csv_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('base_csv_path', models.TextField()),
                ('nodes_csv_path', models.TextField()),
                ('edges_csv_path', models.TextField()),
                ('graphml_path', models.TextField()),
                ('base_graph_path', models.TextField()),
                ('density_graph_path', models.TextField()),
                ('atlas_region_graph_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='templateclass',
            name='key_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarityviz.TokenUpload'),
        ),
    ]
