# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarityviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenCompute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('orientation', models.CharField(max_length=3)),
                ('num_points', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='templateclass',
            name='key_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarityviz.TokenCompute'),
        ),
        migrations.DeleteModel(
            name='TokenUpload',
        ),
        migrations.AddField(
            model_name='plot',
            name='token_compute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarityviz.TokenCompute'),
        ),
    ]
