# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarityviz', '0002_auto_20161114_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenCompute',
            new_name='Compute',
        ),
    ]
