# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarityviz', '0003_auto_20161114_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='token',
            field=models.CharField(max_length=30),
        ),
    ]
