FROM jliu118/clarityviz:super-opencv
MAINTAINER Jonathan Liu <jliu118@jhu.edu>

RUN pip install -U scikit-learn \
	&& pip install boto3

RUN pip install clarityviz

RUN wget 'https://github.com/alee156/clviz/blob/master/utils/execute.py'


